INSERT INTO vinilos (id_vin, nombre, artista, genero, anno, precio, formato, color_vinilo, stock, sello, pais, edicion, duracion, descripcion, img) VALUES
(1, 'Saturday Night Wrist', 'Deftones', 'Metal', 2006, 44900, '2LP', 'Negro - Dorado', 10, 'Maverick Records', 'EE.UU.', 'Original', '61:36',
 'El quinto álbum de Deftones mezcla metal alternativo con atmósferas etéreas, consolidando su sonido más experimental.',
 'img/albums/deftones/saturday-night-wrist-cover.jpg'),
(2, 'Blonde', 'Frank Ocean', 'R&B', 2016, 49900, '2LP', 'Beige', 8, 'Boys Don't Cry', 'EE.UU.', 'Edición Limitada', '60:08',
 'Obra maestra introspectiva de Frank Ocean, fusionando R&B, soul y electrónica con letras profundamente personales.',
 'img/albums/frank-ocean/blonde-cover.jpg'),
(3, 'The Bends', 'Radiohead', 'Rock', 1995, 45900, 'LP', 'Negro - Blanco', 12, 'Parlophone', 'Reino Unido', 'Original', '48:37',
 'El segundo álbum de Radiohead marca su transición hacia un sonido más emocional y alternativo con himnos inolvidables.',
 'img/albums/radiohead/the-bends-cover.jpg'),
(4, 'Imaginal Disk', 'Magdalena Bay', 'Electropop', 2021, 39900, 'LP', 'Transparente', 7, 'Labrador', 'EE.UU.', 'Original', '44:23',
 'El dúo Magdalena Bay entrega un viaje synthpop futurista lleno de energía, melodías pegadizas y producción impecable.',
 'img/albums/magdalena-bay/imaginal-disk-cover.jpg'),
(5, 'La Espada y La Pared', 'Los Tres', 'Rock', 1995, 42900, 'LP', 'Plateado', 9, 'EMI Odeón Chile', 'Chile', 'Original', '46:05',
 'Considerado uno de los mejores discos chilenos de los 90, Los Tres mezclan rock, blues y tonadas criollas con identidad única.',
 'img/albums/los-tres/la-espada-y-la-pared-cover.jpg'),
(6, 'Casiopea', 'Casiopea', 'Jazz Fusion', 1979, 47900, 'LP', 'Blanco', 6, 'Alfa Records', 'Japón', 'Original', '42:28',
 'Debut de la legendaria banda japonesa de jazz-fusion Casiopea, con técnica impecable y un sonido adelantado a su época.',
 'img/albums/casiopea/casiopea-cover.jpg'),
(7, 'Thriller', 'Michael Jackson', 'Pop', 1982, 54900, 'LP', 'Negro', 14, 'Epic Records', 'EE.UU.', 'Remaster 2016', '42:19',
 'El álbum más vendido de la historia, con clásicos inmortales como "Billie Jean", "Beat It" y "Thriller".',
 'img/albums/michael-jackson/thriller-cover.jpg'),
(8, 'The Dark Side of the Moon', 'Pink Floyd', 'Rock Progresivo', 1973, 59900, '2LP', 'Negro', 10, 'Harvest Records', 'Reino Unido', 'Remaster 2011', '42:49',
 'Obra conceptual de Pink Floyd que redefinió el rock progresivo con una experiencia sonora única e inmersiva.',
 'img/albums/pink-floyd/the-dark-side-of-the-moon-cover.jpg'),
(9, 'Whole Lotta Red', 'Playboi Carti', 'Hip Hop', 2020, 42900, '2LP', 'Rojo translúcido', 11, 'Interscope Records', 'EE.UU.', 'Original', '62:15',
 'Playboi Carti entrega un sonido experimental y caótico que marcó una nueva era en el trap alternativo.',
 'img/albums/playboi-carti/whole-lotta-red-cover.jpg');

INSERT INTO usuarios (rut, nombre, correo, rol, contrasena) VALUES
('12345678-5', 'Juan Pérez', 'juan.perez@mail.com', 'Cliente', '123456'),
('87654321-K', 'María González', 'maria.gonzalez@mail.com', 'Empleado', '123456'),
('11223344-3', 'Pedro Ramírez', 'pedro.ramirez@mail.com', 'Empleado', '123456'),
('44332211-9', 'Ana Torres', 'admin@heartz.cl', 'Admin', '123456'),
('55667788-0', 'Luis Fernández', 'cliente@heartz.cl', 'Cliente', '123456');
